### ISSUE TITLE
NuGet package doesn't seem to install binary

### ISSUE THREAD

**Issue by ParaSwarm** [cccsdh/NLog.MongoDB20#2]
Installing this package from NuGet doesn't seem to install the binary. I've tried with two different solutions. It will indeed install the dependencies (nLog, etc), but it doesn't seem to do anything besides that.

I realize this problem is NuGet-specific and not related to the product itself, but I'm not sure where else to send this.

**Comment by cccsdh** [comment]
Just ran a nuget on new project to test this.   Looks like it picked up all requirements and the NLog.MongoDB20.    Project was targeting .net 4.5.1   What .net framework are you targeting?

**Comment by ParaSwarm** [comment]
Yep, just noticed that too. That seems to have been the problem. 

Unfortunately, our project cannot target 4.5.1 at this time, so I've had to downgrade the framework version for this library and manually build it.

Thanks for the help and response.
